version: '2'
services:
    angular2app-mongodb:
        container_name: angular2app-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/angular2app/mongodb/:/data/db/
